# Site settings
title: Guillaume Isabelle X
description: Experiment with Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: JGIsabelle Art
user_description: I'm a Software Engineer and painter from Canada, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of artificially augmented my traditional acrylic painting with neural network
user_title: Software Engineer, Painter
email: x@guillaumeisabelle.com
# twitter_username: lorem_ipsum
instagram_username: jgisabelleart
facebook_username: jgisabelleart
linkedin_username: jgisabelleart
github_username:  jgwill
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
